//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Engage.Dnn.Publish.Controls {
    
    
    public partial class Captchas {
        
        /// <summary>
        /// InvisibleCaptcha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.Web.UI.WebControls.DnnCaptcha InvisibleCaptcha;
        
        /// <summary>
        /// TimeoutCaptcha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.Web.UI.WebControls.DnnCaptcha TimeoutCaptcha;
        
        /// <summary>
        /// StandardCaptcha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DotNetNuke.Web.UI.WebControls.DnnCaptcha StandardCaptcha;
    }
}
